In [42]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [7]:
with np.load('spec_repr/c/03_BN1-129-Eb_comp.npz') as data:
    a = data


In [16]:
pd.DataFrame(data)

0
0    repr
1  labels

In [54]:
import numpy as np

data = np.load('spec_repr/c/03_BN1-129-Eb_comp.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])
    print(lst)
#pd.DataFrame(data['repr'])
#pd.DataFrame(data['labels'])
#pd.DataFrame(data['repr'][4])

repr
[[0.08185231 0.0870002  0.03215288 ... 0.00214449 0.00072434 0.00038493]
 [0.08126334 0.08683451 0.03303173 ... 0.00407887 0.00823323 0.01475024]
 [0.07999146 0.085692   0.03552334 ... 0.00503003 0.01008796 0.00837059]
 ...
 [0.01822574 0.00910706 0.01401938 ... 0.00069604 0.00059076 0.00030668]
 [0.0181685  0.00956586 0.01409088 ... 0.00011143 0.0008023  0.0008596 ]
 [0.01818174 0.00968616 0.01413244 ... 0.01238595 0.01226943 0.01406121]]
['repr', 'labels']
labels
[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 

In [58]:
data['labels'].shape

(962, 6, 21)

In [60]:
pd.DataFrame(data['labels'][:,:][3])

0    1    2    3    4    5    6    7    8    9   ...   11   12   13   14  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   
5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    15   16   17   18   19   20  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  0.0  0.0  

[6 rows x 21 columns]