In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [7]:
import numpy as np

data = np.load('../data/spec_repr/c/00_BN1-129-Eb_comp.npz', allow_pickle=True)
lst = data.files

for item in lst:
    print(item)
    print(data[item])
    print(lst)

repr
[[2.40780880e-03 3.91222980e-02 3.19249043e-02 ... 2.85023482e-03
  2.68717525e-03 2.64643099e-03]
 [4.04591766e-03 3.96381044e-02 3.19348539e-02 ... 1.43570959e-04
  2.51468985e-04 4.45551639e-04]
 [6.76193601e-03 4.05425399e-02 3.21376234e-02 ... 6.13858178e-04
  5.42455000e-04 8.47776359e-04]
 ...
 [6.69731827e-02 1.82040410e-02 5.96915684e-02 ... 1.04330124e-04
  2.45646044e-04 1.39634278e-04]
 [6.67434400e-02 1.55236641e-02 6.04809685e-02 ... 4.62488144e-04
  3.45210230e-04 4.65716601e-04]
 [6.66640027e-02 1.43043917e-02 6.07719245e-02 ... 1.47702072e-04
  8.82992787e-05 2.11445882e-04]]
['repr', 'labels']
labels
[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
 

In [8]:
pd.DataFrame(data['labels'][:, :][961])


0    1    2    3    4    5    6    7    8    9   ...   11   12   13   14  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    15   16   17   18   19   20  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  0.0  0.0  

[6 rows x 21 columns]

In [9]:
data['labels'].shape

(962, 6, 21)